### PR TITLE
Upgrade to hybrid element.

### PR DESCRIPTION
**Pull request by Mihaiii**
For https://github.com/Starcounter/RebelsLounge/issues/140

### CODE REVIEW

**Comment by Mihaiii** [comment]
@PatrykSzwer Hmmm, the checks are failing. I clicked on "Details", but can't figure out why. Do you understand why?

**Comment by PatrykSzwer** [comment]
@tomalec probably will be the best one here to answer/explain.

**Comment by Mihaiii** [comment]
`github-markdown.css` was deleted in order to make the page look like in the [demo](https://juicy.github.io/juicy-dom-tree-view/) .

**Comment by tomalec** [comment]
Speaking of travis, check https://github.com/Juicy/juicy-dom-tree-view/commit/7e77f1800dc8f775c6f3308b4b3ee5d99903ecfe, we need to update node version to latest stable

**Comment by Mihaiii** [comment]
@tomalec Thank you!
Tests are passing in Chrome, but not on Firefox, where I get an error in console:
`TypeError: host.createShadowRoot is not a function` .
It gets to that line because `host.attachShadow` is falsy.

**Comment by Mihaiii** [comment]
I spent too much time on this already and have to move on to other things. 
I need help with this one, sorry. 
@tomalec Could you please have a look when possible?

**Comment by Mihaiii** [comment]
Tests are passing now for Chrome, Firefox, Safari, but not for IE (which we no longer support).
@PatrykSzwer I think this is ready for a review.

**Review by PatrykSzwer — APPROVED** [review]
Since test are passing and everything is working, LGTM

**Pull request merged**
